<?php

namespace Database\Seeders;

use App\Models\Course;
use App\Models\Department;
use Illuminate\Database\Seeder;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        // Get department IDs using 'code' as identifier
        $depts = Department::pluck('id', 'code')->toArray();

        $this->command->info('Available departments: ' . implode(', ', array_keys($depts)));

        $courses = [
            // COE (Mech) Third Year
            [
                'course_code' => 'EM-31005',
                'course_name' => 'Engineering Mathematics V',
                'department_code' => 'ME',
                'lecturer_name' => 'Dr. Kya Kya Hlaing / Daw Su Win',
                'credits' => 3,
                'year' => 'Third Year',
                'semester' => 'First Semester',
                'academic_year' => '2025-2026',
                'room' => 'F-06',
                'schedule_day' => 'Monday',
                'schedule_time' => '09:00',
                'schedule_end_time' => '09:50',
            ],
            [
                'course_code' => 'Met-31043',
                'course_name' => 'Engineering Materials',
                'department_code' => 'ME',
                'lecturer_name' => 'Dr. Htay Htay Win',
                'credits' => 3,
                'year' => 'Third Year',
                'semester' => 'First Semester',
                'academic_year' => '2025-2026',
                'room' => 'F-06',
                'schedule_day' => 'Monday',
                'schedule_time' => '10:00',
                'schedule_end_time' => '10:50',
            ],
            [
                'course_code' => 'ME-31025',
                'course_name' => 'Theory of Machines I',
                'department_code' => 'ME',
                'lecturer_name' => 'Dr. Aung Kyaw Soe',
                'credits' => 3,
                'year' => 'Third Year',
                'semester' => 'First Semester',
                'academic_year' => '2025-2026',
                'room' => 'F-06',
                'schedule_day' => 'Wednesday',
                'schedule_time' => '08:00',
                'schedule_end_time' => '08:50',
            ],
            [
                'course_code' => 'ME-31013',
                'course_name' => 'Thermodynamics I',
                'department_code' => 'ME',
                'lecturer_name' => 'Dr. Yin Yin Aye',
                'credits' => 3,
                'year' => 'Third Year',
                'semester' => 'First Semester',
                'academic_year' => '2025-2026',
                'room' => 'F-06',
                'schedule_day' => 'Friday',
                'schedule_time' => '09:00',
                'schedule_end_time' => '09:50',
            ],
            [
                'course_code' => 'ME-31014',
                'course_name' => 'Strength of Materials I',
                'department_code' => 'ME',
                'lecturer_name' => 'Daw Kya Kya Hlaing / Daw Su Win',
                'credits' => 3,
                'year' => 'Third Year',
                'semester' => 'First Semester',
                'academic_year' => '2025-2026',
                'room' => 'F-06',
            ],
            [
                'course_code' => 'ME-31016',
                'course_name' => 'Fluid Mechanics I',
                'department_code' => 'ME',
                'lecturer_name' => 'Daw Thu Zar Oo',
                'credits' => 3,
                'year' => 'Third Year',
                'semester' => 'First Semester',
                'academic_year' => '2025-2026',
                'room' => 'F-06',
            ],
            // CEIT Fifth Year
            [
                'course_code' => 'CEIT-51023',
                'course_name' => 'Computer Architecture I',
                'department_code' => 'CS',
                'lecturer_name' => 'Dr. Theingi Myint',
                'credits' => 3,
                'year' => 'Fifth Year',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'room' => '1-3-7',
                'schedule_day' => 'Monday',
                'schedule_time' => '08:00',
                'schedule_end_time' => '08:50',
            ],
            [
                'course_code' => 'CEIT-51061',
                'course_name' => 'Embedded System I',
                'department_code' => 'CS',
                'lecturer_name' => 'Dr. Nay Min Htaik',
                'credits' => 3,
                'year' => 'Fifth Year',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'room' => '1-3-7',
                'schedule_day' => 'Tuesday',
                'schedule_time' => '08:00',
                'schedule_end_time' => '08:50',
            ],
            [
                'course_code' => 'CEIT-51033',
                'course_name' => 'Artificial Intelligence',
                'department_code' => 'CS',
                'lecturer_name' => 'Dr. Khaing Thanda Swe',
                'credits' => 4,
                'year' => 'Fifth Year',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'room' => '1-3-7',
                'schedule_day' => 'Wednesday',
                'schedule_time' => '08:00',
                'schedule_end_time' => '08:50',
            ],
            [
                'course_code' => 'CEIT-51026',
                'course_name' => 'Digital Image Processing I',
                'department_code' => 'CS',
                'lecturer_name' => 'Dr. Pyone Pyone Khin',
                'credits' => 3,
                'year' => 'Fifth Year',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'room' => '1-3-7',
                'schedule_day' => 'Thursday',
                'schedule_time' => '08:00',
                'schedule_end_time' => '08:50',
            ],
            [
                'course_code' => 'CEIT-51010',
                'course_name' => 'Wireless and Mobile Communication I',
                'department_code' => 'CS',
                'lecturer_name' => 'Daw Ei Phyu Sin Win',
                'credits' => 3,
                'year' => 'Fifth Year',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'room' => '1-3-7',
                'schedule_day' => 'Wednesday',
                'schedule_time' => '13:00',
                'schedule_end_time' => '13:50',
            ],
            [
                'course_code' => 'E-51001',
                'course_name' => 'English',
                'department_code' => 'CS',
                'lecturer_name' => 'Daw Ohnmar Khine / Daw Thidar Aye',
                'credits' => 2,
                'year' => 'Fifth Year',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'room' => 'F-10',
                'schedule_day' => 'Wednesday',
                'schedule_time' => '11:00',
                'schedule_end_time' => '11:50',
            ],
            [
                'course_code' => 'IT-51010',
                'course_name' => 'Wireless and Mobile Communication (Lab)',
                'department_code' => 'CS',
                'lecturer_name' => 'Daw Ei Phyu Sin Win',
                'credits' => 1,
                'year' => 'Fifth Year',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'room' => '1-3-7',
                'schedule_day' => 'Monday',
                'schedule_time' => '13:00',
                'schedule_end_time' => '13:50',
            ],
            [
                'course_code' => 'IT-51033',
                'course_name' => 'Artificial Intelligence (Lab)',
                'department_code' => 'CS',
                'lecturer_name' => 'Dr. Khaing Thanda Swe',
                'credits' => 1,
                'year' => 'Fifth Year',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'room' => '1-3-7',
                'schedule_day' => 'Thursday',
                'schedule_time' => '13:00',
                'schedule_end_time' => '13:50',
            ],
            // Civil Engineering Fifth Year
            [
                'course_code' => 'CE-51024',
                'course_name' => 'Design of Steel Structure I',
                'department_code' => 'CE',
                'lecturer_name' => 'Dr. Su Myat Mon',
                'credits' => 3,
                'year' => 'Fifth Year',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'schedule_day' => 'Monday',
                'schedule_time' => '08:00',
                'schedule_end_time' => '08:50',
            ],
            [
                'course_code' => 'CE-51022',
                'course_name' => 'Construction Engineering and Management',
                'department_code' => 'CE',
                'lecturer_name' => 'Dr. Nann Su Le Mya Thwin',
                'credits' => 3,
                'year' => 'Fifth Year',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'schedule_day' => 'Tuesday',
                'schedule_time' => '08:00',
                'schedule_end_time' => '08:50',
            ],
            [
                'course_code' => 'CE-51014',
                'course_name' => 'Design of Concrete Structure I',
                'department_code' => 'CE',
                'lecturer_name' => 'Daw Mi Ko Theint',
                'credits' => 4,
                'year' => 'Fifth Year',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'schedule_day' => 'Friday',
                'schedule_time' => '08:00',
                'schedule_end_time' => '08:50',
            ],
            [
                'course_code' => 'CE-51008',
                'course_name' => 'Environmental Engineering III',
                'department_code' => 'CE',
                'lecturer_name' => 'Dr. May Ei Nandar Soe',
                'credits' => 3,
                'year' => 'Fifth Year',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'schedule_day' => 'Monday',
                'schedule_time' => '14:00',
                'schedule_end_time' => '14:50',
            ],
            [
                'course_code' => 'CE-51032',
                'course_name' => 'Contracts, Specifications and Estimation I',
                'department_code' => 'CE',
                'lecturer_name' => 'Daw Poe Zar Ni Aung',
                'credits' => 3,
                'year' => 'Fifth Year',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
            ],
            [
                'course_code' => 'CE-51036',
                'course_name' => 'River and Coastal Engineering',
                'department_code' => 'CE',
                'lecturer_name' => 'Not Assigned',
                'credits' => 3,
                'year' => 'Fifth Year',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'schedule_day' => 'Friday',
                'schedule_time' => '14:00',
                'schedule_end_time' => '14:50',
            ],
            // CS Courses
            [
                'course_code' => 'CS101',
                'course_name' => 'Introduction to Programming',
                'department_code' => 'CS',
                'lecturer_name' => 'Dr. Aye Aye',
                'credits' => 3,
                'year' => 'First Year',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'room' => 'Lab A-101',
                'schedule_day' => 'Monday',
                'schedule_time' => '09:00',
                'schedule_end_time' => '11:00',
            ],
            [
                'course_code' => 'CS102',
                'course_name' => 'Programming Fundamentals',
                'department_code' => 'CS',
                'lecturer_name' => 'Dr. Aye Aye',
                'credits' => 3,
                'year' => 'First Year',
                'semester' => 'Second Semester',
                'academic_year' => '2024-2025',
                'room' => 'Lab A-101',
                'schedule_day' => 'Wednesday',
                'schedule_time' => '09:00',
                'schedule_end_time' => '11:00',
            ],
            [
                'course_code' => 'CS201',
                'course_name' => 'Data Structures',
                'department_code' => 'CS',
                'lecturer_name' => 'Dr. Kyaw Kyaw',
                'credits' => 3,
                'year' => 'Second Year',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'room' => 'Room 201',
                'schedule_day' => 'Tuesday',
                'schedule_time' => '10:00',
                'schedule_end_time' => '12:00',
            ],
            [
                'course_code' => 'CS301',
                'course_name' => 'Database Systems',
                'department_code' => 'CS',
                'lecturer_name' => 'Dr. Phyo Thu Zar Tun',
                'credits' => 4,
                'year' => 'Third Year',
                'semester' => 'First Semester',
                'academic_year' => '2024-2025',
                'room' => 'Lab B-201',
                'schedule_day' => 'Monday',
                'schedule_time' => '13:00',
                'schedule_end_time' => '16:00',
            ],
        ];

        $count = 0;
        $skipped = 0;

        foreach ($courses as $course) {
            $departmentId = $depts[$course['department_code']] ?? null;

            if ($departmentId) {
                Course::updateOrCreate(
                    ['course_code' => $course['course_code']],
                    [
                        'course_name' => $course['course_name'],
                        'department_id' => $departmentId,
                        'lecturer_name' => $course['lecturer_name'],
                        'credits' => $course['credits'],
                        'year' => $course['year'],
                        'semester' => $course['semester'],
                        'academic_year' => $course['academic_year'],
                        'room' => $course['room'] ?? null,
                        'schedule_day' => $course['schedule_day'] ?? null,
                        'schedule_time' => $course['schedule_time'] ?? null,
                        'schedule_end_time' => $course['schedule_end_time'] ?? null,
                        'is_active' => true,
                    ]
                );
                $count++;
            } else {
                $this->command->warn("Skipped: {$course['course_code']} - Department '{$course['department_code']}' not found");
                $skipped++;
            }
        }

        $this->command->info("✅ $count courses seeded successfully!");
        if ($skipped > 0) {
            $this->command->warn("⚠️ $skipped courses skipped.");
        }
    }
}
